# Site settings
title: Samuel Holt Web Developer
email: samuel.holt@gmx.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a front-end web developer based in Wellington, New Zealand
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samuel-holt.github.io" # the base hostname & protocol for your site
twitter_username: SamuelHoltNZ
github_username:  samuel-holt

# Build settings
markdown: kramdown
